### ISSUE TITLE
Cryptomatte crashing maya batch on Linux

### ISSUE THREAD

**Issue by chittyren** [Psyop/CryptomatteArnold#2]
Hello,

I'm experiencing an issue using Cryptomatte Arnold that is causing batch renders to crash on Linux. 
 We are primarily a Windows/OSX environment and use the cloud rendering service Zync (who uses linux).  After several days of back and forth with Zync's support, they were able to confirm the issue was being caused when using the two latest releases of Cryptomatte Arnold (1.1.0-ai5.0.1.0 & 1.0.0-ai5.0.1.0).  The issue occurs when one or more of the Cryptomatte specific AOVs are active.  While not ideal, we do have a work-around in place, which is to downgrade to alShaders2, 2.0.0b4 release and use Maya2018.4.

Attached is a zip file containing a curated log file from the cloud instance (indicated which parts were cut) as well as the scene and HDR asset used for testing.  If you'd like I can post the full log file.

**In-House Environment**:
Windows 10
Maya 2018.2 & 2018.4
MtoA 3.0.1.1

**Zync Environment (from log)**:
CentOS Linux 7 (Core), Linux kernel 4.15.0-1019-gcp
MayaIO2018.4
MtoA 3.0.1.1

Any thoughts or insight into this would be greatly appreciated.  I'd be happy to provide any additional information or assets if needed.

Thanks in advance,
-Alex

[20181206_CryptomatteArnold_Issue.zip](https://github.com/Psyop/CryptomatteArnold/files/2653847/20181206_CryptomatteArnold_Issue.zip)

**Comment by jonahfriedman** [comment]
Sorry that we never responded to this. However I think this is probably ok now as Cryptomatte has been shipping with Arnold on Linux for some time. Please feel free to reopen if it's not.
