### ISSUE TITLE
Remove deprecated API calls relying on the default universe

### ISSUE THREAD

**Issue by sebastienblor** [Psyop/CryptomatteArnold#3]
The cryptomatte code is using several API calls that are now deprecated, and that are relying on the default (null) universe instead of using the proper one. 

That's the case for the functions below :

- AiNodeLookUpByName
- AiUniverseGetOptions 
- AiNode 
- AiUniverseGetNodeIterator

They should all have an additional AtUniverse argument, which requires to change several files in the code

**Comment by jonahfriedman** [comment]
Fixed in 1.1.2
